// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyg8pS4IeGg3bmUyBW0r1auKoFgYAJbDs',
    appId: '1:395265077014:web:89cecf9d367a4a9da46a37',
    messagingSenderId: '395265077014',
    projectId: 'first-project-69502',
    authDomain: 'first-project-69502.firebaseapp.com',
    storageBucket: 'first-project-69502.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_FTtf1mYi9BNLWBYGh7gQRwdsdXFXd40',
    appId: '1:395265077014:android:9c5b4b126716b959a46a37',
    messagingSenderId: '395265077014',
    projectId: 'first-project-69502',
    storageBucket: 'first-project-69502.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa9AamcEPP7BAfTSIj5KFGyAkf_o5cgjE',
    appId: '1:395265077014:ios:8c7d9dc0d82f8fc0a46a37',
    messagingSenderId: '395265077014',
    projectId: 'first-project-69502',
    storageBucket: 'first-project-69502.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyg8pS4IeGg3bmUyBW0r1auKoFgYAJbDs',
    appId: '1:395265077014:web:433c5d5907b3a4e7a46a37',
    messagingSenderId: '395265077014',
    projectId: 'first-project-69502',
    authDomain: 'first-project-69502.firebaseapp.com',
    storageBucket: 'first-project-69502.firebasestorage.app',
  );
}
